# Generated by Django 3.2 on 2021-04-06 16:53

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=videos.models.get_filename, validators=[videos.models.video_validator]),
        ),
    ]
