# Generated by Django 3.1.7 on 2021-04-06 05:17

from django.db import migrations, models
import music.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('cover', models.ImageField(upload_to=music.models.get_up_path)),
                ('artist', models.CharField(blank=True, max_length=40)),
                ('album', models.CharField(blank=True, max_length=40)),
                ('file', models.FileField(upload_to=music.models.get_filename)),
            ],
        ),
    ]
